### ISSUE TITLE
hashing_method not defined

### ISSUE THREAD

**Issue by varioous** [hochstrasserio/wirecard#22]
The hashing_method when initializing the Context object (Context::HASHING_HMAC)

**Comment by haraldernst** [comment]
Are you using the packagist composer package? It seems to be an old version on https://packagist.org/packages/hochstrasserio/wirecard

Try using the github package. Add the repository manually to your compose.json:

```
 "repositories": [
        {
       "type": "vcs",
       "url": "https://github.com/hochstrasserio/wirecard.git"
     }
   ],

**Comment by CHH** [comment]
Hi,

thanks for reporting this. I've not made a new release just yet, but I can say that v1.0.0 is right around the corner.

In the meantime you can help test the next release by requiring the `dev-master` release like this in your `composer.json`:

```
"hochstrasserio/wirecard": "dev-master"
```

**Comment by CHH** [comment]
@varioous I just tagged `v1.0.0`, should show up on Packagist now.

**Comment by varioous** [comment]
No it works perfect! Thanks for fast support :)

Also a Note: i have to use this composer file, that also the correct guzzelhttp library is loaded:

`{
    "require": {
        "hochstrasserio/wirecard": "^0.2.0",
        "guzzlehttp/guzzle": "^6.2"
    }
}
`

Befor only the "guzzlehttp/psr7" was loaded.

Greets,
Harald

**Comment by CHH** [comment]
@varioous yes, the Guzzle dependency has to be explicit. It's intentional that the library doesn't require any HTTP library. This is because I want to leave that choice completely up to you, so you can decide what you want/have to use in your project's environment. Often it's that a project already uses an infrastructure for making HTTP requests built on top of an HTTP client, e.g. Guzzle 5 or Guzzle 6, and I want you to be able to reuse that infrastructure.
