### ISSUE TITLE
Plans for integrating Wirecard Payment Page v2?

### ISSUE THREAD

**Issue by Chris8934** [hochstrasserio/wirecard#41]
Hallo,

The Wirecard Checkout Page is deprecated and will not work after 30.09.2020.
See https://www.wirecard.com/de/checkout-optimierung/#wirecard-payment-page

Is there any plan for integrating the Wirecard Payment Page v2?
Or another solution to use it after 30.09.2020?

Greetings

**Comment by JanSlabon** [comment]
They'd changed so much that it will be IMHO impossible to have a single framework allowing both. I tried [their own](https://github.com/wirecard/paymentSDK-php) without success because of lacks in their documentation and inconsitency of documentation, code and demos... This is written by someone, who had build it but never tried to give it to a foreign developer. 

My conclusion: Thank @CHH for his great work of the now outdated SDK! As of now use simple REST calls, do not try to integrate their solution as you did before (e.g. "embedded" is a completely new workflow not comparable to the previous way) but use their hosted payment page. Keep it simple. The more you think of or try things out the more problems you will encounter in their "new" system! Never send their support information about wrong, inconstistent documentation or behavior - they will never take them seriously and it's your lost time.

I need to stop here, because I'm getting bad feelings the more I think back... ;-)

**Comment by Chris8934** [comment]
Thanks for the reply. I still hope to find an all in one SDK to make integration as easy as possible.

**Comment by CHH** [comment]
Thanks for answering this @JanSlabon. Truth is, that I don't have any project that uses this code anymore.

Also, I'm wholeheartedly recommending Stripe to anyone who asks me, since they've become GA in Austria & Germany. They feature most of the relevant payment methods (at least in beta) and are vastly easier to work with.

**Comment by Chris8934** [comment]
Thanks for the fast response and the advise
